### ISSUE TITLE
您好，豆丁的docin文件head 和 page分开的那种docin格式，会解压成swf吗？

### ISSUE THREAD

**Issue by nissansz** [you8023/downloadDocin#1]
您好，豆丁的docin文件head 和 page分开的那种docin格式，会解压成swf吗？

**Comment by you8023** [comment]
> 您好，豆丁的docin文件head 和 page分开的那种docin格式，会解压成swf吗？

你好，能提供个例子吗，因为自己在下载的时候似乎没遇到过你说的这种情况

**Comment by nissansz** [comment]
怎么发文件给你看？微信 nlanguage

**Comment by you8023** [comment]
> 怎么发文件给你看？微信 nlanguage

你贴个网址就好啦^_^

**Comment by nissansz** [comment]
https://www.docin.com/p-2323272910.html

**Comment by you8023** [comment]
> https://www.docin.com/p-2323272910.html

不好意思，这个文档为付费文档，目前该脚本只能下载能够预览的部分，是无法绕过付费机制的。但能够预览的部分亲测是没有任何问题，可以下载的，没有出现你描述的情况；
而如果你已经付了费的话，就可以直接下载了，也不需要我这个脚本了(๑＞ڡ＜)☆。

**Comment by nissansz** [comment]
只需要head.docin, page.docin分開的格式，如何解壓成swf即可

**Comment by you8023** [comment]
> 只需要head.docin, page.docin分開的格式，如何解壓成swf即可

不好意思，我没太懂你的意思，swf不是一个动画的格式吗？head.docin又是啥|ू･ω･` )
