### ISSUE TITLE
为何我在浏览器“检查”的相应位置看到的是canvas

### ISSUE THREAD

**Issue by LuDreamst** [you8023/downloadDocin#5]
[请问在使用浏览器的“检查”功能时，我对应位置看到的是canvas，但您的截图里显示的是图片格式，这是为什么？（此脚本现仍可正常使用）
![image](https://user-images.githubusercontent.com/53106447/163355624-54ea1fed-934b-423e-b662-939a58b35c67.png)

**Comment by you8023** [comment]
应该是因为网站改源码了hhhhh，我最开始写这个脚本的时候确实是图片直接在HTML标签内的。
不过其底层实现逻辑似乎没变，依然是使用flash_param_hzq字段存储其sid，然后作为参数拼凑成对应的图片网址（详见readme）；使用js代码请求该图片网址再使用canvas标签进行渲染而成，因此只需要拿到该图片网址也可以下载，这也是脚本依然生效的原因（因为其并非使用img标签爬取图片，而是对其图片网址进行深层次分析，再进行requests请求。无论网页元素如何改变，只要其底层逻辑没变，即图片存放的网址字段不变，该脚本依旧生效）

**Comment by LuDreamst** [comment]
> 应该是因为网站改源码了hhhhh，我最开始写这个脚本的时候确实是图片直接在HTML标签内的。 不过其底层实现逻辑似乎没变，依然是使用flash_param_hzq字段存储其sid，然后作为参数拼凑成对应的图片网址（详见readme）；使用js代码请求该图片网址再使用canvas标签进行渲染而成，因此只需要拿到该图片网址也可以下载，这也是脚本依然生效的原因（因为其并非使用img标签爬取图片，而是对其图片网址进行深层次分析，再进行requests请求。无论网页元素如何改变，只要其底层逻辑没变，即图片存放的网址字段不变，该脚本依旧生效）

感谢您的详细解答~
